# Travis CI (MIT License) configuration file for the solitude WordPress theme.
# @link https://travis-ci.org/

# For use with the solitude WordPress theme.
# @link https://github.com/shubham9411/solitude

# Ditch sudo and use containers.
# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure

language:
    - php

php:
    - 5.3
    - 5.4

before_script:
    - pear install PHP_CodeSniffer
    - git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress

script:
    - phpcs --standard=WordPress